"""
RAG Service - Flashcard Service Client
HTTP client to save generated flashcards to the flashcard-service.
"""

import httpx
from app.config import get_settings
from app.models.schemas import FlashcardItem


async def save_flashcards_to_service(
    user_id: str,
    title: str,
    flashcards: list[FlashcardItem],
    auth_token: str | None = None,
) -> str | None:
    """
    Create a flashcard deck + cards via flashcard-service API.
    
    Flashcard-service routes:
    - POST /api/flashcard-decks           → create deck
    - POST /api/flashcard-decks/:deckId/cards  → create card in deck
    """
    settings = get_settings()
    base = settings.flashcard_service_url
    headers = {"Content-Type": "application/json"}
    if auth_token:
        headers["Authorization"] = f"Bearer {auth_token}"

    async with httpx.AsyncClient(timeout=30.0) as client:
        # 1. Create deck
        deck_resp = await client.post(
            f"{base}/api/flashcard-decks",
            json={
                "title": title,
                "description": f"Auto-generated by AI — {len(flashcards)} cards",
                "isPublic": False,
                "userId": user_id,
            },
            headers=headers,
        )

        if deck_resp.status_code not in (200, 201):
            print(f"[RAG] Failed to create deck: {deck_resp.status_code} {deck_resp.text}")
            return None

        deck_data = deck_resp.json()
        deck_id = deck_data.get("data", {}).get("id") or deck_data.get("id")
        if not deck_id:
            print(f"[RAG] No deck ID in response: {deck_data}")
            return None

        # 2. Create cards — correct route: /api/flashcard-decks/:deckId/cards
        for card in flashcards:
            await client.post(
                f"{base}/api/flashcard-decks/{deck_id}/cards",
                json={
                    "frontContent": card.front_content,
                    "backContent": card.back_content,
                    "exampleSentence": card.example_sentence or "",
                },
                headers=headers,
            )

        return deck_id
