-- ====================================================================
-- Seed: Cambridge IELTS 16 - Reading Test 4 into Assessment Service
-- ====================================================================

DO $$
DECLARE
  v_test_id UUID;
  v_section_id UUID;
  v_passage_id UUID;
  v_qorder INT;
BEGIN
  -- Create test
  INSERT INTO assessment_db.tests (id, title, slug, status, duration_in_minutes, english_test_type_id, created_at, updated_at)
  VALUES (gen_random_uuid(), 'Cambridge IELTS 16 - Reading Test 4', 'cambridge-ielts-16-reading-test-4', 'PUBLISHED', 60, '11111111-1111-1111-1111-111111111111', NOW(), NOW())
  RETURNING id INTO v_test_id;
  
  INSERT INTO assessment_db.test_skills (test_id, skill) VALUES (v_test_id, 'READING');

  -- ═══════ SECTION 1: Passage 1 — Roman Tunnels ═══════
  INSERT INTO assessment_db.sections (id, test_id, title, skill, order_index)
  VALUES (gen_random_uuid(), v_test_id, 'Passage 1 — Roman Tunnels', 'READING', 0)
  RETURNING id INTO v_section_id;

  INSERT INTO assessment_db.passages (id, section_id, content, passage_order)
  VALUES (gen_random_uuid(), v_section_id, E'Roman Tunnels\n\nThe fruit of the Persians'' work was the qanat, a gently sloping tunnel that carried water from an underground water source to the surface, irrigating fields along the way. The qanat was an important technological development as it relied on gravity rather than mechanical pumps. In the early first millennium BCE, the Persians introduced the qanat method of tunnel construction, which consisted of placing posts over a hill in a straight line, to ensure that the tunnel kept to its route. Vertical shafts were sunk at regular intervals along the line and the tunnel was excavated from the bottom of each shaft.\n\nThe Romans, too, were great tunnel builders. A key Roman technique was to work from both ends of a tunnel at once. In terms of accuracy, perhaps the finest example of ancient tunnel engineering is the tunnel on the Greek island of Samos, built in the sixth century BCE. Designed by the engineer Eupalinos, the one-kilometre tunnel was dug from both ends and the two halves met in the middle with only a small margin of error. This was a remarkable feat of surveying.\n\nModern tunnel building relies on technology that would have been unimaginable to ancient engineers. Tunnel boring machines (TBMs), which can excavate tunnels with diameters up to 17 metres, use a large rotating cutter head to break through rock and soil. The Channel Tunnel, linking Britain and France beneath the English Channel, was completed in 1994 using eleven TBMs. At 50 kilometres, it is one of the longest underwater tunnels in the world and carries both rail passengers and freight.\n\nMore recently, Elon Musk''s Boring Company has proposed the development of a network of underground tunnels in cities such as Los Angeles to help alleviate traffic congestion. The company claims that its machines can bore tunnels at significantly lower costs than traditional methods, although critics question whether the approach is practical on a large scale.', 1)
  RETURNING id INTO v_passage_id;

  v_qorder := 1;
  -- Gap fills
  INSERT INTO assessment_db.questions (id, section_id, passage_id, test_id, question_type, question_text, content, answer, explanation, question_order) VALUES
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'GAP_FILL', 'The Persians used _____ placed over a hill to direct the tunnelling.', '{"text":"The Persians used _____ placed over a hill to direct the tunnelling."}', '{"text":["posts"]}', 'The passage states: placing posts over a hill in a straight line.', 1),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'GAP_FILL', 'The tunnel on the island of Samos was designed by the engineer _____.', '{"text":"The tunnel on the island of Samos was designed by the engineer _____."}', '{"text":["Eupalinos"]}', 'The passage states: Designed by the engineer Eupalinos.', 2),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'GAP_FILL', 'The Channel Tunnel is approximately _____ kilometres long.', '{"text":"The Channel Tunnel linking Britain and France is approximately _____ kilometres long."}', '{"text":["50"]}', 'The passage states: At 50 kilometres.', 3),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'GAP_FILL', 'Vertical _____ were sunk at regular intervals along the qanat line.', '{"text":"Vertical _____ were sunk at regular intervals along the qanat line."}', '{"text":["shafts"]}', 'The passage states: Vertical shafts were sunk at regular intervals.', 4),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'GAP_FILL', 'The Boring Company aims to reduce traffic _____.', '{"text":"The Boring Company aims to reduce traffic _____ in cities like Los Angeles."}', '{"text":["congestion"]}', 'The passage states: to help alleviate traffic congestion.', 5);

  -- True/False/Not Given
  INSERT INTO assessment_db.questions (id, section_id, passage_id, test_id, question_type, question_text, content, answer, explanation, question_order) VALUES
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'TRUE_FALSE_NOT_GIVEN', 'The qanat method required mechanical pumps to transport water.', '{"text":"The qanat method required mechanical pumps to transport water."}', '{"correctAnswer":"FALSE"}', 'The qanat relied on gravity rather than mechanical pumps.', 6),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'TRUE_FALSE_NOT_GIVEN', 'The Romans sometimes worked from both ends of a tunnel simultaneously.', '{"text":"The Romans sometimes worked from both ends of a tunnel simultaneously."}', '{"correctAnswer":"TRUE"}', 'A key Roman technique was to work from both ends of a tunnel at once.', 7),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'TRUE_FALSE_NOT_GIVEN', 'Elon Musk''s Boring Company has received universal praise.', '{"text":"Elon Musk''s Boring Company has received universal praise for its tunnel proposals."}', '{"correctAnswer":"FALSE"}', 'Critics question whether the approach is practical on a large scale.', 8),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'TRUE_FALSE_NOT_GIVEN', 'The Channel Tunnel carries both passengers and freight.', '{"text":"The Channel Tunnel carries both passengers and freight."}', '{"correctAnswer":"TRUE"}', 'The passage states: carries both rail passengers and freight.', 9),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'TRUE_FALSE_NOT_GIVEN', 'The Boring Company claims its tunnels cost more than traditional methods.', '{"text":"The Boring Company claims its tunnels cost more than traditional methods."}', '{"correctAnswer":"FALSE"}', 'The passage says significantly lower costs.', 10);

  -- MCQ
  INSERT INTO assessment_db.questions (id, section_id, passage_id, test_id, question_type, question_text, content, answer, explanation, question_order) VALUES
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'MULTIPLE_CHOICE', 'Key feature of modern TBMs?', '{"text":"What is a key feature of modern Tunnel Boring Machines (TBMs)?","options":["They use explosives to break through rock","They use a rotating cutter head to excavate","They require manual labour to operate","They can only work in soft soil"]}', '{"correctIndex":1}', 'TBMs use a large rotating cutter head to break through rock and soil.', 11),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'MULTIPLE_CHOICE', 'What does the passage say about the Samos tunnel?', '{"text":"What does the passage say about the Samos tunnel?","options":["It was the longest tunnel in the ancient world","It was dug from both ends with remarkable accuracy","It was built by Roman engineers","It was used primarily for transporting goods"]}', '{"correctIndex":1}', 'It was dug from both ends with remarkable accuracy.', 12),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'MULTIPLE_CHOICE', 'How many TBMs for Channel Tunnel?', '{"text":"The Channel Tunnel was completed using how many TBMs?","options":["6","8","11","15"]}', '{"correctIndex":2}', 'Completed using eleven TBMs.', 13);

  -- ═══════ SECTION 2: Passage 2 — Reading in a Whole New Way ═══════
  INSERT INTO assessment_db.sections (id, test_id, title, skill, order_index)
  VALUES (gen_random_uuid(), v_test_id, 'Passage 2 — Reading in a Whole New Way', 'READING', 1)
  RETURNING id INTO v_section_id;

  INSERT INTO assessment_db.passages (id, section_id, content, passage_order)
  VALUES (gen_random_uuid(), v_section_id, E'Reading in a Whole New Way\n\nLook around on your next plane trip. The iPad is the new pacifier for babies and toddlers. Younger school-aged children read stories on smartphones; older kids don''t read at all, but hunch over video games. Parents and other passengers read on tablets or skim a flotilla of email and news feeds. Unbeknown to most of us, an invisible, game-changing transformation links everyone in this picture: the neuronal circuit that underlies the brain''s ability to read is subtly, rapidly changing — and this has implications for everyone from the pre-reading toddler to the expert adult.\n\nThe act of reading is not natural. We were never born to read. Human beings invented literacy only a few thousand years ago. And with this invention, we rearranged the very organisation of our brain, which in turn expanded the ways we were able to think, which altered the intellectual evolution of our species. The reading circuit is not given to us through a genetic blueprint like vision or language; it needs an environment to develop. Furthermore, it will adapt to that environment''s requirements — from different writing systems used across cultures to the predominant medium in which the written word is presented. If the dominant medium of our time is digital, the reading circuit will adapt accordingly.\n\nThe problem is that many features of the current digital environment work against deep reading processes. For example, the sheer volume of information and the speed at which we are expected to process it militate against the kind of slow, deliberate, cognitively demanding processes that compose a significant portion of the reading circuit: critical analysis, the development of personal insight, and reflection. There is an emerging body of research that indicates that reading on screens promotes a shift in cognitive patterns from deep reading to speed reading, skimming, and word-spotting.\n\nMaryanne Wolf, a cognitive neuroscientist at Tufts University, has long studied the science of the reading brain. Wolf argues that we should not assume that critical analysis, empathy, and other deep reading processes will transfer automatically from a print-based reading brain to one that has adapted to screen-based reading. In her view, we need to cultivate a "bi-literate" brain — one that is equally capable of deep reading on paper and efficient reading on screens.', 1)
  RETURNING id INTO v_passage_id;

  -- MCQ
  INSERT INTO assessment_db.questions (id, section_id, passage_id, test_id, question_type, question_text, content, answer, explanation, question_order) VALUES
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'MULTIPLE_CHOICE', 'Writer''s main point in first paragraph?', '{"text":"What is the writer''s main point in the first paragraph?","options":["Our use of technology is having a hidden effect on us","Technology can be used to help youngsters to read","Travellers should be encouraged to use technology on planes","Playing games is a more popular use of technology than reading"]}', '{"correctIndex":0}', 'An invisible, game-changing transformation links everyone.', 14),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'MULTIPLE_CHOICE', 'What does the digital environment work against?', '{"text":"According to the passage, what does the digital environment work against?","options":["Physical exercise","Deep reading processes","Social interaction","Creative writing"]}', '{"correctIndex":1}', 'Many features of the current digital environment work against deep reading processes.', 15),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'MULTIPLE_CHOICE', 'What does Wolf mean by bi-literate brain?', '{"text":"What does Maryanne Wolf mean by a bi-literate brain?","options":["A brain that can read in two languages","A brain capable of both deep reading on paper and efficient reading on screens","A brain that reads twice as fast as normal","A brain that only reads on digital devices"]}', '{"correctIndex":1}', 'Equally capable of deep reading on paper and efficient reading on screens.', 16);

  -- T/F/NG
  INSERT INTO assessment_db.questions (id, section_id, passage_id, test_id, question_type, question_text, content, answer, explanation, question_order) VALUES
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'TRUE_FALSE_NOT_GIVEN', 'Humans have always had a natural ability to read.', '{"text":"Humans have always had a natural ability to read."}', '{"correctAnswer":"FALSE"}', 'The act of reading is not natural. We were never born to read.', 17),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'TRUE_FALSE_NOT_GIVEN', 'The reading circuit is genetically determined.', '{"text":"The reading circuit is genetically determined, like vision or language."}', '{"correctAnswer":"FALSE"}', 'The reading circuit is not given through a genetic blueprint.', 18),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'TRUE_FALSE_NOT_GIVEN', 'Research suggests screen reading promotes deep reading.', '{"text":"Research suggests that reading on screens promotes deep reading."}', '{"correctAnswer":"FALSE"}', 'Screen reading promotes a shift from deep reading to speed reading, skimming.', 19),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'TRUE_FALSE_NOT_GIVEN', 'The reading circuit needs an environment to develop.', '{"text":"The reading circuit needs an environment to develop."}', '{"correctAnswer":"TRUE"}', 'It needs an environment to develop.', 20),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'TRUE_FALSE_NOT_GIVEN', 'Wolf believes critical analysis transfers automatically.', '{"text":"Wolf believes critical analysis will automatically transfer from print to screen reading."}', '{"correctAnswer":"FALSE"}', 'We should not assume that critical analysis will transfer automatically.', 21),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'TRUE_FALSE_NOT_GIVEN', 'Human beings invented literacy thousands of years ago.', '{"text":"Human beings invented literacy thousands of years ago."}', '{"correctAnswer":"TRUE"}', 'Human beings invented literacy only a few thousand years ago.', 22);

  -- Gap fills
  INSERT INTO assessment_db.questions (id, section_id, passage_id, test_id, question_type, question_text, content, answer, explanation, question_order) VALUES
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'GAP_FILL', 'Reading rearranged the organisation of our _____.', '{"text":"The invention of reading rearranged the organisation of our _____."}', '{"text":["brain"]}', 'We rearranged the very organisation of our brain.', 23),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'GAP_FILL', 'Wolf is a neuroscientist at _____ University.', '{"text":"Maryanne Wolf is a cognitive neuroscientist at _____ University."}', '{"text":["Tufts"]}', 'Maryanne Wolf, a cognitive neuroscientist at Tufts University.', 24),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'GAP_FILL', 'Cognitively _____ processes.', '{"text":"The volume of information works against slow, deliberate, cognitively _____ processes."}', '{"text":["demanding"]}', 'Cognitively demanding processes.', 25),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'GAP_FILL', 'Screen reading promotes skimming and _____-spotting.', '{"text":"Screen-based reading promotes skimming and _____-spotting."}', '{"text":["word"]}', 'Speed reading, skimming, and word-spotting.', 26);

  -- ═══════ SECTION 3: Passage 3 — AI and Predictions ═══════
  INSERT INTO assessment_db.sections (id, test_id, title, skill, order_index)
  VALUES (gen_random_uuid(), v_test_id, 'Passage 3 — AI and Predictions', 'READING', 2)
  RETURNING id INTO v_section_id;

  INSERT INTO assessment_db.passages (id, section_id, content, passage_order)
  VALUES (gen_random_uuid(), v_section_id, E'The Future of Artificial Intelligence in Forecasting\n\nArtificial intelligence is now capable of predicting the future — at least in certain well-defined areas. AI systems can forecast which patients are likely to develop specific diseases, which convicted criminals are likely to reoffend, which students are at risk of dropping out, and even which couples are heading for divorce. In many cases, their predictions are significantly more accurate than those made by human experts working in the same fields.\n\nPolice departments in several US cities, for example, have adopted predictive policing software. These systems use machine learning algorithms to analyze historical crime data and identify "hot spots" where crimes are most likely to occur. Researchers have found that such algorithms outperform experienced crime analysts at forecasting where burglaries and car thefts are most likely to happen.\n\nIn medicine, AI systems have shown promising results in predicting health outcomes. An algorithm developed at Stanford University can examine a chest X-ray and diagnose pneumonia more accurately than a panel of expert radiologists. Similarly, Google''s DeepMind has developed an AI system that can predict acute kidney injury up to 48 hours before it occurs — potentially giving doctors crucial time to intervene.\n\nDespite these impressive achievements, people remain reluctant to trust AI predictions. Studies consistently show that when given the choice, most individuals prefer to rely on human judgment, even when they are told that the algorithm is more accurate. This phenomenon has been termed "algorithm aversion." Researchers have found that people lose confidence in an algorithm more quickly after seeing it make a mistake than they would lose confidence in a human expert who made the same error.\n\nIf AI is to benefit society by improving predictions across domains, researchers must first understand why people resist algorithmic recommendations. Only by addressing the psychological barriers to the adoption of AI predictions can we hope to harness the full potential of these powerful tools.', 1)
  RETURNING id INTO v_passage_id;

  -- MCQ
  INSERT INTO assessment_db.questions (id, section_id, passage_id, test_id, question_type, question_text, content, answer, explanation, question_order) VALUES
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'MULTIPLE_CHOICE', 'Best heading for this passage?', '{"text":"Which is the best heading for this passage?","options":["The dangers of relying on machines","The superiority of AI predictions over those made by humans","How AI algorithms are created","Why humans will always be better at predictions"]}', '{"correctIndex":1}', 'The passage discusses how AI predictions outperform human ones.', 27),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'MULTIPLE_CHOICE', 'What can DeepMind AI predict?', '{"text":"What can Google''s DeepMind AI predict?","options":["Heart attacks","Acute kidney injury","Lung cancer","Diabetes"]}', '{"correctIndex":1}', 'DeepMind can predict acute kidney injury up to 48 hours before it occurs.', 28),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'MULTIPLE_CHOICE', 'What must happen for AI to benefit society?', '{"text":"According to the passage, what must happen for AI to benefit society?","options":["AI must become perfect","Researchers must understand why people resist algorithmic recommendations","Governments must force people to use AI","AI must replace all human decision-making"]}', '{"correctIndex":1}', 'Researchers must first understand why people resist algorithmic recommendations.', 29),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'MULTIPLE_CHOICE', 'What do predictive policing algorithms analyze?', '{"text":"What do predictive policing algorithms analyze?","options":["Social media posts","Historical crime data","Facial recognition data","Witness testimonies"]}', '{"correctIndex":1}', 'They use machine learning to analyze historical crime data.', 30);

  -- T/F/NG
  INSERT INTO assessment_db.questions (id, section_id, passage_id, test_id, question_type, question_text, content, answer, explanation, question_order) VALUES
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'TRUE_FALSE_NOT_GIVEN', 'Predictive policing software has been used in some US cities.', '{"text":"Predictive policing software has been used in some US cities."}', '{"correctAnswer":"TRUE"}', 'Police departments in several US cities have adopted predictive policing software.', 31),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'TRUE_FALSE_NOT_GIVEN', 'People are equally willing to forgive AI and human mistakes.', '{"text":"People are equally willing to forgive mistakes by AI and human experts."}', '{"correctAnswer":"FALSE"}', 'People lose confidence in an algorithm more quickly than in a human expert.', 32),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'TRUE_FALSE_NOT_GIVEN', 'AI can forecast which students are at risk of dropping out.', '{"text":"AI systems can forecast which students are at risk of dropping out."}', '{"correctAnswer":"TRUE"}', 'The passage says: which students are at risk of dropping out.', 33),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'TRUE_FALSE_NOT_GIVEN', 'DeepMind predicts kidney injury up to 72 hours in advance.', '{"text":"DeepMind''s system can predict kidney injury up to 72 hours in advance."}', '{"correctAnswer":"FALSE"}', 'The passage says up to 48 hours, not 72.', 34),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'TRUE_FALSE_NOT_GIVEN', 'Most people prefer human judgment even when AI is more accurate.', '{"text":"Most people prefer human judgment even when told algorithms are more accurate."}', '{"correctAnswer":"TRUE"}', 'Most individuals prefer to rely on human judgment.', 35),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'TRUE_FALSE_NOT_GIVEN', 'AI predictions are always less accurate than human experts.', '{"text":"AI predictions are always less accurate than human experts."}', '{"correctAnswer":"FALSE"}', 'Their predictions are significantly more accurate than those made by human experts.', 36);

  -- Gap fills
  INSERT INTO assessment_db.questions (id, section_id, passage_id, test_id, question_type, question_text, content, answer, explanation, question_order) VALUES
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'GAP_FILL', 'Stanford algorithm diagnoses _____ from chest X-rays.', '{"text":"An algorithm from Stanford University can diagnose _____ from chest X-rays."}', '{"text":["pneumonia"]}', 'Diagnose pneumonia more accurately than expert radiologists.', 37),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'GAP_FILL', 'Reluctance to trust AI is called algorithm _____.', '{"text":"The reluctance to trust AI predictions is known as algorithm _____."}', '{"text":["aversion"]}', 'This phenomenon has been termed algorithm aversion.', 38),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'GAP_FILL', 'Predictive policing identifies crime _____.', '{"text":"Predictive policing uses machine learning to identify crime _____."}', '{"text":["hot spots"]}', 'Identify hot spots where crimes are most likely to occur.', 39),
  (gen_random_uuid(), v_section_id, v_passage_id, v_test_id, 'GAP_FILL', 'People lose confidence in algorithms faster than in _____ experts.', '{"text":"People lose confidence in algorithms more quickly than in _____ experts after seeing errors."}', '{"text":["human"]}', 'Lose confidence more quickly than in a human expert.', 40);

  RAISE NOTICE 'Reading test created with ID: %', v_test_id;
END $$;
