"""
LLM service — unified text-generation interface across providers.

Primary: Gemini Flash (Google AI Studio) — supports MULTIPLE keys, round-robined
         and skipped on rate-limit (429) to multiply free-tier limits.
Fallback: Ollama (local)

The fallback to Ollama triggers automatically when:
  - llm_provider != "gemini", OR
  - no Gemini keys are configured, OR
  - every configured Gemini key raises / times out / is rate-limited
"""

import json
from typing import Optional

import httpx


GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta/models"

# Round-robin pointer across configured Gemini keys (in-memory, per process). Lets
# multiple free-tier keys share the load and skip past a rate-limited one.
_key_cursor = 0


async def _generate_gemini(
    prompt: str,
    api_key: str,
    model: str,
    temperature: float,
    max_tokens: int,
    timeout: float,
    json_mode: bool = False,
) -> str:
    url = f"{GEMINI_BASE}/{model}:generateContent?key={api_key}"
    generation_config = {
        "temperature": temperature,
        "maxOutputTokens": max_tokens,
        "topP": 0.9,
        # Gemini 2.5 models are "thinking" models: by default the model spends
        # part of maxOutputTokens on internal reasoning, which can leave 0 tokens
        # for the actual answer → empty `parts`. Disable thinking so the whole
        # budget goes to the visible response.
        "thinkingConfig": {"thinkingBudget": 0},
    }
    if json_mode:
        # Force a syntactically valid JSON response (used for lesson/translate).
        generation_config["responseMimeType"] = "application/json"
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": generation_config,
    }
    async with httpx.AsyncClient(timeout=timeout) as client:
        resp = await client.post(url, json=payload)
        # Older models reject thinkingConfig — retry once without it.
        if resp.status_code == 400 and "thinking" in resp.text.lower():
            payload["generationConfig"].pop("thinkingConfig", None)
            resp = await client.post(url, json=payload)
        resp.raise_for_status()
        data = resp.json()

    # Gemini response format: candidates[0].content.parts[0].text
    candidates = data.get("candidates", [])
    if not candidates:
        return ""
    parts = candidates[0].get("content", {}).get("parts", [])
    return "".join(p.get("text", "") for p in parts).strip()


async def _generate_ollama(
    prompt: str,
    base_url: str,
    model: str,
    temperature: float,
    max_tokens: int,
    timeout: float,
    json_mode: bool = False,
) -> str:
    body = {
        "model": model,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": temperature,
            "num_predict": max_tokens,
            # num_ctx is the TOTAL window (prompt + output) in Ollama. The lesson
            # prompt is long and the output can be large; 4096 truncated the JSON
            # mid-response. Size the window to comfortably fit both.
            "num_ctx": max(8192, max_tokens + 2048),
            "top_p": 0.9,
        },
    }
    if json_mode:
        # Force Ollama to emit valid JSON (used for lesson/translate generation).
        body["format"] = "json"
    async with httpx.AsyncClient(timeout=timeout) as client:
        resp = await client.post(f"{base_url}/api/generate", json=body)
        resp.raise_for_status()
        data = resp.json()
    return str(data.get("response", "")).strip()


async def generate_text(
    prompt: str,
    settings,
    *,
    temperature: float = 0.7,
    max_tokens: int = 1024,
    timeout: float = 60.0,
    json_mode: bool = False,
    usage: Optional[dict] = None,
) -> str:
    """Generate text from the configured LLM with automatic fallback to Ollama.

    Set json_mode=True when the prompt asks for a JSON object — both providers are
    then constrained to emit valid JSON (much more reliable parsing). Leave it
    False for free-form prose (e.g. Q&A answers).

    Pass a dict as `usage` to learn which provider/model actually produced the
    text: on success it is filled with {"provider": ..., "model": ...}; if every
    provider failed it is left as {"provider": "none", "model": None}. Lets the
    caller log a single definitive "content generated by X" line.
    """
    if usage is not None:
        usage["provider"], usage["model"] = "none", None

    provider = (settings.llm_provider or "ollama").lower()

    keys = settings.gemini_keys
    if provider == "gemini" and keys:
        global _key_cursor
        n = len(keys)
        start = _key_cursor % n
        print(f"[LLM] Using Gemini model: {settings.gemini_model} ({n} key(s), temp={temperature}, max_tokens={max_tokens})")
        # Round-robin across all keys, skipping to the next on rate-limit/error so a
        # single exhausted free-tier key doesn't drop us to Ollama prematurely.
        for offset in range(n):
            idx = (start + offset) % n
            try:
                text = await _generate_gemini(
                    prompt,
                    keys[idx],
                    settings.gemini_model,
                    temperature,
                    max_tokens,
                    timeout,
                    json_mode=json_mode,
                )
                if text:
                    _key_cursor = (idx + 1) % n  # next request starts at the following key
                    print(f"[LLM] Gemini key {idx + 1}/{n} responded OK ({len(text)} chars)")
                    if usage is not None:
                        usage["provider"], usage["model"] = "gemini", settings.gemini_model
                    return text
                print(f"[LLM] Gemini key {idx + 1}/{n} returned empty — trying next key")
            except Exception as e:
                msg = str(e).lower()
                rate = "429" in msg or "quota" in msg or "rate" in msg or "resource_exhausted" in msg
                print(f"[LLM] Gemini key {idx + 1}/{n} {'rate-limited' if rate else 'error'} ({type(e).__name__}) — trying next key")
        _key_cursor = (start + 1) % n
        print(f"[LLM] All {n} Gemini key(s) exhausted — falling back to Ollama")
    else:
        print(f"[LLM] Skipping Gemini (provider={provider!r}, keys={len(keys)}) — going straight to Ollama")

    print(f"[LLM] Using Ollama model: {settings.ollama_model} at {settings.ollama_base_url}")
    try:
        text = await _generate_ollama(
            prompt,
            settings.ollama_base_url,
            settings.ollama_model,
            temperature,
            max_tokens,
            timeout,
            json_mode=json_mode,
        )
        print(f"[LLM] Ollama ({settings.ollama_model}) responded OK ({len(text)} chars)")
        if usage is not None:
            usage["provider"], usage["model"] = "ollama", settings.ollama_model
        return text
    except Exception as e:
        print(f"[LLM] Ollama fallback also failed: {e}")
        return ""


def extract_json_object(text: str) -> Optional[dict]:
    """Best-effort JSON extraction from an LLM response that may contain stray prose."""
    if not text:
        return None
    start, end = text.find("{"), text.rfind("}") + 1
    if start < 0 or end <= start:
        return None
    try:
        return json.loads(text[start:end])
    except json.JSONDecodeError:
        return None
